import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { load } from 'cheerio'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectRoot = path.resolve(__dirname, '..')
const workspaceRoot = path.resolve(projectRoot, '..')

const outputFile = path.join(projectRoot, 'src', 'data', 'syncedContent.js')

const FINANCIAL_URL = 'https://icd.gov.ae/financial-information/'
const MEDIA_URL = 'https://icd.gov.ae/media-centre/'

const normalizeText = (value = '') => value.replace(/\s+/g, ' ').trim()

async function fetchWithFallback(url, fallbackFileName) {
  try {
    const response = await fetch(url, {
      headers: {
        'user-agent':
          'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124 Safari/537.36',
      },
    })

    if (!response.ok) {
      throw new Error(`HTTP ${response.status} for ${url}`)
    }

    return await response.text()
  } catch (error) {
    const fallbackPath = path.join(workspaceRoot, fallbackFileName)
    try {
      const fallback = await fs.readFile(fallbackPath, 'utf8')
      console.warn(
        `[sync-content] Could not fetch ${url}. Using fallback file ${fallbackPath}.`,
      )
      return fallback
    } catch {
      throw new Error(
        `[sync-content] Failed to fetch ${url} and fallback ${fallbackPath} is missing. Original error: ${error.message}`,
      )
    }
  }
}

function parseFinancialReports(html) {
  const $ = load(html)
  const yearByPane = new Map()

  $('#myTab [data-bs-target]').each((_, tabButton) => {
    const target = $(tabButton).attr('data-bs-target')
    const yearText = normalizeText($(tabButton).text())

    if (!target || !yearText) {
      return
    }

    const paneId = target.replace('#', '')
    yearByPane.set(paneId, yearText)
  })

  const reports = []

  $('#myTabContent .tab-pane').each((_, pane) => {
    const paneId = $(pane).attr('id') || ''
    const year = yearByPane.get(paneId) || ''

    $(pane)
      .find('.tcr-i-flex')
      .each((__, row) => {
        const title = normalizeText($(row).find('.reportname').first().text())

        if (!title) {
          return
        }

        const sectionClass = $(row).closest('.ti-annual, .ti-interim').attr('class') || ''
        let category = 'Other'

        if (sectionClass.includes('ti-annual')) {
          category = 'Annual'
        } else if (sectionClass.includes('ti-interim')) {
          category = 'Interim'
        }

        const links = []

        $(row)
          .find('.reportpdf a[href]')
          .each((___, anchor) => {
            const href = $(anchor).attr('href')
            if (!href) {
              return
            }

            const label = normalizeText($(anchor).text()) || 'Open'
            const url = href.startsWith('http') ? href : `https://icd.gov.ae${href}`
            links.push({ label, url })
          })

        reports.push({
          year,
          category,
          title,
          links,
        })
      })
  })

  reports.sort((a, b) => {
    const yearDiff = (Number.parseInt(b.year, 10) || 0) - (Number.parseInt(a.year, 10) || 0)
    if (yearDiff !== 0) {
      return yearDiff
    }

    const categoryDiff = a.category.localeCompare(b.category)
    if (categoryDiff !== 0) {
      return categoryDiff
    }

    return a.title.localeCompare(b.title)
  })

  return reports
}

function parseMediaVideos(html) {
  const $ = load(html)
  const sections = []

  $('.video__wrapper').each((_, wrapper) => {
    const sectionTitle = normalizeText(
      $(wrapper).find('.icd__video__title h2').first().text(),
    )

    const items = []

    $(wrapper)
      .find('.video_thumb')
      .each((__, card) => {
        const title = normalizeText($(card).find('h4').first().text())
        const thumbnail = $(card).find('img.video__thumbnail').attr('src') || ''
        const alt =
          normalizeText($(card).find('img.video__thumbnail').attr('alt') || '') ||
          title
        const videoUrl = $(card).find('.video__btn').attr('data-video-url') || ''

        if (!title || !videoUrl) {
          return
        }

        items.push({ title, thumbnail, alt, videoUrl })
      })

    if (items.length > 0) {
      sections.push({ sectionTitle, items })
    }
  })

  return sections
}

function buildOutputFile(financialReports, mediaVideos) {
  const generatedAt = new Date().toISOString()

  return `/* This file is auto-generated by scripts/sync-content.mjs. */\n/* eslint-disable */\n\nexport const contentSyncedAt = ${JSON.stringify(generatedAt)}\n\nexport const syncedFinancialReports = ${JSON.stringify(financialReports, null, 2)}\n\nexport const syncedMediaVideos = ${JSON.stringify(mediaVideos, null, 2)}\n`
}

async function main() {
  try {
    const [financialHtml, mediaHtml] = await Promise.all([
      fetchWithFallback(FINANCIAL_URL, 'financial-information.html'),
      fetchWithFallback(MEDIA_URL, 'media-centre.html'),
    ])

    const financialReports = parseFinancialReports(financialHtml)
    const mediaVideos = parseMediaVideos(mediaHtml)

    const output = buildOutputFile(financialReports, mediaVideos)
    await fs.writeFile(outputFile, output, 'utf8')

    console.log(
      `[sync-content] Wrote ${financialReports.length} financial entries and ${mediaVideos.reduce((sum, section) => sum + section.items.length, 0)} media videos to ${outputFile}`,
    )
  } catch (error) {
    console.error(error.message)
    process.exitCode = 1
  }
}

main()
